language: go
install:
- go get -v github.com/spf13/hugo
script:
- hugo version
- make build
branches:
  only:
  - master
env:
  global:
    secure: bloZQJOvkocViO354KKp8j9aMCyHd+j1M7VM2CNIm+Qm1NVKaQngbeN+fgr0w7dHSAGJDzlxVHAN/My46BI05MLijM/anMdQQyAYJjPUDBRzKoxP708jgzMlDkBBYhlDlwgXtPt+ScnlPn+L3db1Nggms1ZbU0VoxMGcJ1+vlB1X38C6GaLtT8FCdoJBubQOVijZDyKx54rB7VejR85qLneonA3XGJJLgkuxAQxBHByiQJDCNFeABJc5Cyie2NNscbDyibwmmtKa7XW/rbzfUCc41uaQMxJa0QCrfxOXbaKUx3ngc48pMz9gyTpd6qZ10ta3Rqf4FM3AXSHtF+2eGDSjv8Y5G7L0OFAk0QFDvpLZjPpB6UDVLg0VyAnnytQA75ulvP8S6JW7E3jDYs5M6UNoMXmTIVxSbHNJ/Qp9tARt6SgHcA9/u+v5HKbBmxI9v6oNepELBhn8K+S1mtmkqYNQPDwkyVLOrwqUXpA6USgI57zWLMP+N4CU1f2biWgnLCDxJ9JEJCYDQZoFeCL2l4FdKn8C6bLoU2xR5qRKT9KHkvuRi4IZY5IhQPqI8HBT6OuVyUe3yCPW6vs6auQwJcoj9yxwC22OWWl6zhWo9SFmp2WSw9oN1MRW8Sp5hDD4teKC38xEZ9WpsC9at2JH3tzqyfgGxm4K8+W8BSBdmGA=
 secure: "Jg+c+trtuW960/J2Klx3/BwQ46yP8cNfTE4KiKrVOdmZEAKgVrpct27pd3KQNmAoK2MG837r6b2woOuzrgEj1QZAcUfbI2c9GX+FhKmNTbkcXffIaLnaZEdQz9az4QjGEa90GL49lP/HxiFb+4Te9OCQveoe5jAp8mcF9fnlCaUFUqgDoaLkl3dzncitFFXsijY7LZFZ53lQuO/TXfIFV3zOGX8aMXIewmbawHDtJkisjUlTcXLs6fELZv82LpHxcDLiHf6eaqpC/nbUiFMq8bVQw4/ynYZX7ff9wdD5RqoAtiPl6xx/ZB5Y3/De5O4TtEChQCsa0B8aTC52uoTUndmgbXaEW/Pi0kcQdX+21nFiIyGTK+KkTgCmt0htugjN8QoVlggqX6HN/YDSCIW4LVldGKdkKN6sQGO2R3tdkSc03T7rUKcBKlm6jM3DdZCE6nVfm62havK9uzlnTHgCGTZv5aSsS8HfWnkoQ3j6jHlcPrk/kLt8zm+cihnzpyf0SjZaOjxIG9tl2+G2gsfyaO7bnBN490cej6juQ5aPfviXZ12xay9SP6CseNPu++fQMvwpWw/sWi90DL+mJrSjKfzeXVnU8fxt8iFH3zi1ODS61wRPeNnHgngfouWwM1XvyA2PfPDV8MZiPhnX7iYPhQnaEnRRV2w9Er050955SRA="