language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: w0N0Apo5bvKe6bdz34FnN/KwhxTCQPDVlB6+OGo5hC+YiixRXc5+bt+ew8ZTzGz6mwVBeL2Zgp/ygHn3kIRDOYeT6CYEj565bvK4a389OPJuo6RPD49Cq/2im+WgsWc3Muwr023NDWc9hw6FlQz8mPyn+M11XtjE2ECuQkJbLRGPN6T81CacA+mhUv2QRQ5+8/0dSeMkk3vPEqyCQYDI1VeUPOzSvvQeSBbaS7bQe6th4JHr2xj0byxfmZv4FgVM854aTzSlmh+DeuDtSwAnLyVs9O+hvEUhkEMeHzHdhWptwmpK5i+bLf17wYbQTkIfZDlQ40CLV8xlB5Pw79sMSBbc3Pght+PE3N6CAAPXkhuh6/4+qJPIx5RTz36bWjREe1xM1Kfboiie65+XzNqWS8aQNtTrc4qLTGtJt5X05Q/v30NepH8E2NTlQVJeDucJfI5kzninQQaXFnfWGsCbQGrqENEI4LATCw/fS6W6/swRF6JjqNpShdisdRLn5iHos7+uTZA7DNL3yB/MhDf5OlHX6Hqw4mcL1NSjU8lBTFNr1ly/QVWkvHwAQZX1J9p+ekwz2P4VipPLdbIqmYStksd8DaTwtUCLvF4yEGBFJ+zAH493PiVC8MaaEhQOzDJIT8Z7pZfuGJR+tVXjFPWqovid5gOkK43RwyQp84Y4sHo=
  - secure: ynPWbwYN4CLre/3Ul8RbTtp0oJwCJch+4mamGczibooj8GWizHAF1kWE1m8odcBbUWYQJ7zh5l0F4qSHR3VJzKOVt2wH3sG0zggEEcpNGvkk/+R4Bqfj6H1FeVFXEAnRgZ2uCr0UU8DjY5X1qBFpAs56h3ZHJ1oY+xkz1KvhOYZRBkA7b3ona+H8sakHuotQryI1l0igi8PFmNMwIGZQfB+pDMcrdBfAgTtoBp8AjpAZ1a/r9kTq/2BKLPPR/O3X5g2SPkK8g2fR7c7VOTt+aw059MlLTWqDBktLrLwjd41+5TSSBqLZMEL+UYCjlGfEat/4+BxuorZPhzCCuxrHWObOV4uS2FUmMaPywhGveqIRMjBIPJut/0RC5Ct7bx8H6r6qg/Oer7IeOOh8U5j0bMiatKmF6UVyTD8OQk1T6jzVc18Sbz/KHeW0FO4JK71wwxGABg/keziKMZlxyX0bOXL4rPe40dlHq+rraGDn3xb/GCwWkgVgb1DtpjTD1NwOrNjq/EUXTcUpWUsKeuvseL9SaS6El7VEP+C83xYoU2LvLXzGkXjKW8J/Nmsuomb/uoCfv6SC7M094RjqXHyJA8/4j4KfNjokG8/uzMBuqsWCS8E8YJV2unbD04vpsZjMIydF/X4hiiISYdnBce0CMtN7YoP1divEDTh96HIdOsA=
