language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: A8DfYN6SjzDYYx/KkK6cwtQym/uUF/U5DRWmUiQhRWMWQBXX1y0tO84hxDWpQA6zKhE1P2Cupo5BPl/xCOtdSC0VfebtfJfETjwNIHTe+4ebMr6BkDF/has1D9c+EkB2UJG736Q4HRenpWm1hTzYzOYQ1S7I5jSexsdrPKwvRTKtRkL3pKSyEh31pBIpEa7rQCFv/+ZzluPAjrqaZOYEilCnAW1m2Teci7VjLqcsZlEezeoWvfAx7lSLTPoBz31bA1fygin+vIp8WUejIWrRWIRun0KU7Yt4HzXXkUMjNBGoSafBDPF0ortTWuYCh38tXowuuk9hIEVLzH4wJW6Bc2yiL05seiR2Obq/bJkgTGqnqw2Hcrw6P63NxpCPE3FhTVboyt2hje3B/7XG/5ufI4tJauzZSpZCQ53MNJgzpJCcD+3a7/Lpi9gvkG44pwmGCyA9zH68pjCDnuP+iPlUMyogELr6QGoosNN2yzM4eQRcpbRj2iKSCbi1Ne2yfzDo/bz5xKgfwoGNaZaA1UF3gMXoXWJ0DL4f4Zjk240r75FX/0Du338ToQZub3RoQeuMovCJhSVppE+nA5jXQSMFJHq3dSG4BjcPHrP2fIkHqQyNjrz7JubEio80PNenYhVKksOH+RsaJ+p1irpu9MDHga4pQcjSvsHzajpMKHKWmu8=
  - secure: myf46Z7K/CQG6ihiAnod22UAlB+uURKekZ4VRMm4F083de0AjErAZkLb+OGC7IAWX5C9iUOHbrhjuD1koWIiiy3/jURUOGHXZyN8AsdE0CrqRXByBSDxajMggvvmt++yz/xQpaopSqGB/rlQWGFKSu1ANANkbjB0r8I+0ZEzbppwTN8cV+HaEfMwRrPxhcAXMRyxAmYeZZb4a6/04QQkJAuTKX3cDv2Ynb7/OWb6/hf71A1Gw4O+lQ6wieE/4tEKpkoEZK7ZvuPfW7QMTY3qlhNUAP76h0BNbDHuzi9LGaUTpUsyIG974x77nI3C4mx7+U6t7ddmDfau8lNOEy9hs57pU/uXlOkeAQMls5PiGNVDeLi8M3O+spdLN3J4Nb2tukDs6a/1RiOBChTZShZWj/YyOV8UXGIW99A4bkwoHtYbtC7iulxa+AsbD7kpNocDFA5FUVau1Ielbfli3HwdC7MBWbOoPLIObNlzmcTwSEDOiy/qqfoCIM4V/DAbEj1UghYY2oBPlfGcFEaP92chachjGM7NufeXCD5oeuKbH3lGuV8pkRYUMH9CNQguOfdZVBeqVvo2huBDdXfcg3ZKumM4vuj8FQwj2kWrDGrVKml8moas675ma/1xUFU+zcHsV0Q0S+KEG+CO7tgkD+Z6NItkmSbGj83OHCm1iXCbZek=
